services:
  api:
    build: .
    volumes:
      - ./:/api
    ports:
      - 8080:8080
    working_dir: /api
    tty: true
    command: "bash"

  db:
    image: mysql:8.2.0
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
